### PR TITLE
Fix missing sub->annotation changes

### PR DESCRIPTION
**Pull request by JanSchulz**

### CODE REVIEW

**Comment by JanSchulz** [comment]
Did the rd change by hand...

**Comment by hrbrmstr** [comment]
argh. I totally had that on the mental TODO as well but got caught up
validating the functionality. thx.

**Comment by hrbrmstr** [comment]
I added these directly since I totally admit to not knowing whether github wld take this and automagically merge it to the previous one or not (it prbly would have now that i think of it)

**Comment by JanSchulz** [comment]
Usually, if you merge it into the branch which is the source of the PR (in this case your master branch), the PR is updated. Everything which you do to your branch is reflected in the PR (`rebase` + `push -f` or merges). As I did the PR against your master branch, it would end up in the PR.

**Pull request closed without merging**
